apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: efk-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - kibana.spacemesh.io"
spec:
  rules:
  - host: kibana.spacemesh.io
    http:
      paths:
      - path: /
        backend:
          serviceName: kibana
          servicePort: 443
  - host: elastic.spacemesh.io
    http:
      paths:
      - path: /
        backend:
          serviceName: elasticsearch-client
          servicePort: 9200
