apiVersion: v1
kind: Pod
metadata:
  name: spacemesh-pod
spec:
  containers:
  - name: docker
    image: docker:18.09
    imagePullPolicy: IfNotPresent
    command:
    - cat
    tty: true
    volumeMounts:
      - name: docker
        mountPath: /var/run/docker.sock
  - name: kubectl
    image: lachlanevenson/k8s-kubectl:v1.8.0
    command:
    - cat
    tty: true
  - name: git
    image: alpine/git
    command:
    - cat
    tty: true
  - name: python
    image: spacemeshos/go-spacemesh-python:main
    imagePullPolicy: Always
    command:
    - cat
    tty: true
  volumes:
  - name: docker
    hostPath:
      path: /var/run/docker.sock
