apiVersion: v1
appVersion: 6.4.2
description: A Helm chart for Elasticsearch cluster
maintainers:
- email: alen.komljen@live.com
  name: komljen
  url: https://akomljen.com
name: elasticsearch
sources:
- https://github.com/upmc-enterprises/elasticsearch-operator
version: 0.1.5
